# Generated by Django 5.2.8 on 2025-11-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_category_project_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='relevance',
            field=models.IntegerField(choices=[(1, 'Very Low'), (2, 'Low'), (3, 'Medium'), (4, 'High'), (5, 'Very High')], default=3),
        ),
    ]
