# Generated by Django 5.2.8 on 2025-12-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_project_short_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='📜', max_length=10, verbose_name='Icono/Emoji')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitle', models.CharField(max_length=200, verbose_name='Subtítulo / Organización')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('date', models.DateField(verbose_name='Fecha de obtención')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Enlace (Opcional)')),
            ],
            options={
                'verbose_name': 'Certificado / Proyecto',
                'verbose_name_plural': 'Certificados y Proyectos',
                'ordering': ['-date'],
            },
        ),
    ]
