# Generated by Django 5.2.8 on 2025-12-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_certificate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='certificate',
            options={'ordering': ['-date'], 'verbose_name': 'Certificate / Project', 'verbose_name_plural': 'Certificates & Projects'},
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date',
            field=models.DateField(verbose_name='Date Obtained'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='icon',
            field=models.CharField(default='📜', max_length=10, verbose_name='Icon/Emoji'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='subtitle',
            field=models.CharField(max_length=200, verbose_name='Subtitle / Organization'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Link (Optional)'),
        ),
    ]
