# Generated by Django 5.2.8 on 2026-02-12 19:22

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_certificate_bilingual_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='related_projects',
            field=models.ManyToManyField(blank=True, to='portfolio.project'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='description_en',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description (EN)'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='description_es',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Description (ES)'),
        ),
    ]
