# Generated by Django 5.2.8 on 2026-04-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='icon_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/icons/', verbose_name='Icon SVG/PNG'),
        ),
    ]
