# Generated by Django 5.2.8 on 2026-04-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_certificate_icon_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_type',
            field=models.CharField(choices=[('IMAGE', 'Static Image'), ('THREEJS', 'Three.js Animation'), ('HTML', 'Raw HTML Code')], default='IMAGE', help_text='Select what type of content to display as the project cover.', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='html_content',
            field=models.TextField(blank=True, help_text='Custom HTML/CSS to be rendered as the cover.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='threejs_script',
            field=models.TextField(blank=True, help_text="JavaScript code to initialize the Three.js scene (using a container with ID 'threejs-container-{{project.id}}').", null=True),
        ),
    ]
