# Generated by Django 5.2.8 on 2026-04-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_project_cover_type_project_html_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='html_file',
            field=models.FileField(blank=True, help_text='Upload an .html file for the custom cover content. Takes precedence over the text field.', null=True, upload_to='projects/html/'),
        ),
        migrations.AddField(
            model_name='project',
            name='threejs_file',
            field=models.FileField(blank=True, help_text='Upload a .js file for the Three.js initialization script. Takes precedence over the text field.', null=True, upload_to='projects/threejs/'),
        ),
    ]
