# Generated by Django 5.2.8 on 2026-05-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_project_html_file_project_threejs_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='list_cover_type',
            field=models.CharField(choices=[('IMAGE', 'Static Image'), ('THREEJS', 'Three.js Animation'), ('HTML', 'Raw HTML Code')], default='IMAGE', help_text='Select what type of content to display in the project list (outside view).', max_length=10, verbose_name='List View Cover Type'),
        ),
        migrations.AddField(
            model_name='project',
            name='list_html_content',
            field=models.TextField(blank=True, help_text='Custom HTML/CSS for the list view cover.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='list_html_file',
            field=models.FileField(blank=True, help_text='Upload an .html file for the list view cover. Takes precedence over the text field.', null=True, upload_to='projects/html/'),
        ),
        migrations.AddField(
            model_name='project',
            name='list_image',
            field=models.ImageField(blank=True, help_text='Optional: Different image for the list view. If empty, the main image is used.', null=True, upload_to='projects/list_covers/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='cover_type',
            field=models.CharField(choices=[('IMAGE', 'Static Image'), ('THREEJS', 'Three.js Animation'), ('HTML', 'Raw HTML Code')], default='IMAGE', help_text='Select what type of content to display as the project cover in the detail view.', max_length=10),
        ),
    ]
