# Generated by Django 5.2.8 on 2026-05-23 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_project_list_cover_type_project_list_html_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Show as a prominent button instead of in the dropdown'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_miniproject',
            field=models.BooleanField(default=False, help_text='Mark this as a miniproject.'),
        ),
        migrations.AddField(
            model_name='project',
            name='parent_project',
            field=models.ForeignKey(blank=True, help_text='If this is a miniproject, select its main parent project.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miniprojects', to='portfolio.project'),
        ),
    ]
